<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kategori_barang extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        chek_session();
        date_default_timezone_set("Asia/Bangkok");
        $this->load->model('Kategori_barang_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $kategori_barang = $this->Kategori_barang_model->get_all();

        $data = array(
            'kategori_barang_data' => $kategori_barang
        );

        //$this->template->load('template','kategori_barang_list', $data);

        $this->template->load('admin/template','admin/kategori_barang_list', array(        
        'kategori_barang_data' => $kategori_barang,
        ));
    }

    public function read($id) 
    {
        $row = $this->Kategori_barang_model->get_by_id($id);
        if ($row) {
            $data = array(
		'kd_kategori' => $row->kd_kategori,
		'nama_kategori' => $row->nama_kategori,
	    );
        $this->template->load('admin/template','admin/kategori_barang_read', $data);

        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_barang'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('kategori_barang/create_action'),
	    'kd_kategori' => set_value('kd_kategori'),
	    'nama_kategori' => set_value('nama_kategori'),
	);
        $this->template->load('admin/template','admin/kategori_barang_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kategori' => $this->input->post('nama_kategori',TRUE),
	    );

            $this->Kategori_barang_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('kategori_barang'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Kategori_barang_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('kategori_barang/update_action'),
		'kd_kategori' => set_value('kd_kategori', $row->kd_kategori),
		'nama_kategori' => set_value('nama_kategori', $row->nama_kategori),
	    );
            $this->template->load('admin/template','admin/kategori_barang_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_barang'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('kd_kategori', TRUE));
        } else {
            $data = array(
		'nama_kategori' => $this->input->post('nama_kategori',TRUE),
	    );

            $this->Kategori_barang_model->update($this->input->post('kd_kategori', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('kategori_barang'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Kategori_barang_model->get_by_id($id);

        if ($row) {
            $this->Kategori_barang_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('kategori_barang'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('kategori_barang'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kategori', 'nama kategori', 'trim|required');

	$this->form_validation->set_rules('kd_kategori', 'kd_kategori', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Kategori_barang.php */
/* Location: ./application/controllers/Kategori_barang.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-21 05:42:11 */
/* http://harviacode.com */